version: '3'
services:
  storage:
    image: busybox
    volumes:
      - storage:/var/lib/mysql

  mysql:
    image: mysql:5.7
    command: >
      mysqld
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_bin
    volumes:
      - storage:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: "chat_server"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: ""

volumes:
  storage:
